# This workflow builds and tests a Laravel application

name: Laravel CI

on:
  # Triggers the workflow on push or pull request events to the main branch
  push:
    branches: [ final ]
  pull_request:
    branches: [ final ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Configure PHP version
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0 # Adjust as needed

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      # Install NPM dependencies (if applicable)
      - name: Install NPM dependencies (if applicable)
        run: npm install  # Adjust command if using Yarn

      # Generate application key
      - name: Generate Application Key
        run: php artisan key:generate

      # Migration
      - name: Migration of the table
        run: php artisan migrate

      # Run tests (replace with your actual test command)
      - name: Run Tests
        #run: vendor/bin/phpunit tests/Feature
        run: php artisan test

      - name: Run Project
        run: php artisan serve

      # Additional steps (optional)
      # - Run code styling checks (e.g., with PHP CodeSniffer)
      # - Run static analysis tools
